<?= var_dump($errors) ?>
<form action="http://filevault.loc/Customer/register" method="post">
    <input type="text" name="username" placeholder="Username"><br><br>
    <input type="password" name="password" placeholder="Password"><br><br>
    <input type="text" name="email" placeholder="Email"><br><br>
    <input type="submit" value="Register">
</form>

<a href="http://filevault.loc/Home/index">Nazad na Login</a>
